In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv('banknotes.csv')
df

Variance  Skewness  Curtosis  Entropy  Class
0      3.62160   8.66610   -2.8073 -0.44699      0
1      4.54590   8.16740   -2.4586 -1.46210      0
2      3.86600  -2.63830    1.9242  0.10645      0
3      3.45660   9.52280   -4.0112 -3.59440      0
4      0.32924  -4.45520    4.5718 -0.98880      0
...        ...       ...       ...      ...    ...
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

[1372 rows x 5 columns]

In [2]:
df.shape


(1372, 5)

In [3]:
df.isnull().sum()

Variance    0
Skewness    0
Curtosis    0
Entropy     0
Class       0
dtype: int64

In [4]:
df.columns

Index(['Variance', 'Skewness', 'Curtosis', 'Entropy', 'Class'], dtype='object')

In [5]:
x=df[['Variance', 'Skewness', 'Curtosis', 'Entropy']]
y=df['Class']

In [6]:
x


Variance  Skewness  Curtosis  Entropy
0      3.62160   8.66610   -2.8073 -0.44699
1      4.54590   8.16740   -2.4586 -1.46210
2      3.86600  -2.63830    1.9242  0.10645
3      3.45660   9.52280   -4.0112 -3.59440
4      0.32924  -4.45520    4.5718 -0.98880
...        ...       ...       ...      ...
1367   0.40614   1.34920   -1.4501 -0.55949
1368  -1.38870  -4.87730    6.4774  0.34179
1369  -3.75030 -13.45860   17.5932 -2.77710
1370  -3.56370  -8.38270   12.3930 -1.28230
1371  -2.54190  -0.65804    2.6842  1.19520

[1372 rows x 4 columns]

In [7]:
y

0       0
1       0
2       0
3       0
4       0
       ..
1367    1
1368    1
1369    1
1370    1
1371    1
Name: Class, Length: 1372, dtype: int64

In [8]:
set(y)

{0, 1}

In [9]:
np.unique(y)

array([0, 1], dtype=int64)

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=20)

In [12]:
len(x_train)

1097

In [13]:
x_train.head()

Variance  Skewness  Curtosis   Entropy
370     2.2526    9.9636   -3.1749 -2.994400
722     4.8451    8.1116   -2.9512 -1.472400
434     5.6272   10.0857   -4.2931 -3.814200
122    -1.4572    9.1214    1.7425 -5.124100
1351    1.3183    1.9017   -3.3111  0.065071

In [14]:
from sklearn.tree import DecisionTreeClassifier

In [15]:
classifier=DecisionTreeClassifier()

In [16]:
classifier.fit(x_train,y_train)

DecisionTreeClassifier()

In [17]:
y_pred=classifier.predict(x_test)
y_pred


array([0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0], dtype=int64)

In [18]:
y_test

611     0
545     0
662     0
1139    1
226     0
       ..
681     0
746     0
879     1
1017    1
446     0
Name: Class, Length: 275, dtype: int64

In [19]:
result=pd.DataFrame({'Actual':y_test, 'Predicted':y_pred})
result

Actual  Predicted
611        0          0
545        0          0
662        0          0
1139       1          1
226        0          0
...      ...        ...
681        0          0
746        0          0
879        1          1
1017       1          1
446        0          0

[275 rows x 2 columns]

In [20]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[150   4]
 [  3 118]]


In [21]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.9745454545454545


In [22]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.97      0.98       154
           1       0.97      0.98      0.97       121

    accuracy                           0.97       275
   macro avg       0.97      0.97      0.97       275
weighted avg       0.97      0.97      0.97       275



In [26]:
a=[[2.2504,3.5757,0.35273,0.2836]]
b=[[-1.6677,-7.1535,7.8929,0.96765]]
c=[[-3.56370,-8.38270,12.3930,-1.28230]]
d=[[3.45660,9.52280,-4.0112,-3.59440]]
if(classifier.predict(a)==1):
    print("Original note")
else:
    print("fake note")
    

fake note
